
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-08-26T11:53:13-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "cc5aea5b7bbbacda28b8f3b6e4c15a7365e7147b",
 "version": "0.6.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
