
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-10-21T13:35:51-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "e20f626b87b5bb87d223495a56aefd768272a7ca",
 "version": "2023.10.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
