
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-09-21T12:47:03+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "c71b7dfd934bcd2d250412cb87882ec41ebb01a5",
 "version": "0.4.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
