
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-09-20T16:21:07-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "17bf757ac573e2ca639e7bbb1669e5b96c0b86dd",
 "version": "0.6.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
