
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-05-04T10:48:42-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "56ee81dfd0d4b618f596acbf5b86447a22304e10",
 "version": "0.4.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
