
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "2d18cee3bf9dc91b7d669a65e6e7449c9f9a1b1b",
 "version": "1.0.75"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
