
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-09-25T13:26:58-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "5b49d8d0498363e370480cf80e2196c5e0951ba0",
 "version": "1.4.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
