
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-06-11T16:16:24+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "d0d6be89ca5d37bb0f83469345cf987b55d7171e",
 "version": "3.4.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
