
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-11-10T15:33:39-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "b2f11d026d2c6f806036c050ff5dbd59d6ceb6ec",
 "version": "2023.11.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
